In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [17]:
df = pd.read_csv('/content/drive/MyDrive/데싸 팀플/final_1124.csv',index_col=0,dtype={'jkNo':str,'trNo':str})

In [18]:
df.columns

Index(['age', 'budam', 'chulNo', 'diffUnit', 'hrName', 'hrNo', 'jkName',
       'jkNo', 'meet', 'name', 'ord', 'plcOdds', 'rank', 'rating', 'rcDate',
       'rcDay', 'rcDist', 'rcName', 'rcNo', 'rcTime', 'sex', 'trName', 'trNo',
       'wgBudam', 'wgHr', 'winOdds', 'jkAge', 'jkCareer', 'trCareer', 'track',
       'waterPercent', 'trTime_14', 'trTime_30', 'recent_jinryo', 'recent_ill',
       'wgHr_var', 'y_speed', 'y_ord', 'prdName', 'hrrank', 'ord1Rate',
       'ord2Rate', 'jkord1Rate', 'jkord2Rate', 'trord1Rate', 'trord2Rate'],
      dtype='object')

## 안 쓰기로 한 변수 제거

In [19]:
# 안 쓰기로 한 변수 제거
df.drop(columns=['budam','rcDay','diffUnit','name','track'],inplace=True)
df.columns

Index(['age', 'chulNo', 'hrName', 'hrNo', 'jkName', 'jkNo', 'meet', 'ord',
       'plcOdds', 'rank', 'rating', 'rcDate', 'rcDist', 'rcName', 'rcNo',
       'rcTime', 'sex', 'trName', 'trNo', 'wgBudam', 'wgHr', 'winOdds',
       'jkAge', 'jkCareer', 'trCareer', 'waterPercent', 'trTime_14',
       'trTime_30', 'recent_jinryo', 'recent_ill', 'wgHr_var', 'y_speed',
       'y_ord', 'prdName', 'hrrank', 'ord1Rate', 'ord2Rate', 'jkord1Rate',
       'jkord2Rate', 'trord1Rate', 'trord2Rate'],
      dtype='object')

## 더미변수 처리

In [20]:
# 더미변수(track, meet, 국산외산, rank(제주/한라/나머지))
# rank 구분 - 제주/한라/비제주
df['jeju'] = df['rank'].apply(lambda x: '제주' if '제' in x else ('한라' if '한' in x else '비제주'))

df['jeju']

0         비제주
1         비제주
2         비제주
3         비제주
4         비제주
         ...
106729     제주
106730     제주
106731     제주
106732     제주
106733     제주
Name: jeju, Length: 106734, dtype: object

In [13]:
# track - ordinal 변수 처리
# df['track'].unique()
# 음 근데 이거 필요함?

In [21]:
df['meet2'] = df['meet']

In [22]:
# 더미변수 생성
# track 추가?
df = pd.get_dummies(df,columns=['sex','meet','prdName','jeju'],drop_first=True)

In [23]:
df.columns

Index(['age', 'chulNo', 'hrName', 'hrNo', 'jkName', 'jkNo', 'ord', 'plcOdds',
       'rank', 'rating', 'rcDate', 'rcDist', 'rcName', 'rcNo', 'rcTime',
       'trName', 'trNo', 'wgBudam', 'wgHr', 'winOdds', 'jkAge', 'jkCareer',
       'trCareer', 'waterPercent', 'trTime_14', 'trTime_30', 'recent_jinryo',
       'recent_ill', 'wgHr_var', 'y_speed', 'y_ord', 'hrrank', 'ord1Rate',
       'ord2Rate', 'jkord1Rate', 'jkord2Rate', 'trord1Rate', 'trord2Rate',
       'meet2', 'sex_수', 'sex_암', 'meet_서울', 'meet_제주', 'prdName_외산',
       'jeju_제주', 'jeju_한라'],
      dtype='object')

## train-test split

In [24]:
df

,age,chulNo,hrName,hrNo,jkName,jkNo,ord,plcOdds,rank,rating,...,trord1Rate,trord2Rate,meet2,sex_수,sex_암,meet_서울,meet_제주,prdName_외산,jeju_제주,jeju_한라
0,3,6,알파러너,38647,정동철,080482,1,1.2,국4등급,43,...,0.130435,0.128146,부산경남,1,0,0,0,0,0,0
1,4,5,백두장수,37077,정동철,080482,5,6.0,국6등급,0,...,0.090278,0.125000,부산경남,1,0,0,0,0,0,0
2,3,10,최강클리어,38954,박재이,080546,4,4.5,국6등급,0,...,0.130435,0.128146,부산경남,1,0,0,0,0,0,0
3,4,11,천지킹즈,37279,이희천,080395,3,2.3,국6등급,0,...,0.090278,0.125000,부산경남,1,0,0,0,0,0,0
4,3,3,비케이선더,38935,김철호,080434,2,1.1,국6등급,0,...,0.085366,0.073171,부산경남,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106729,2,7,훈치,3103514,강수한,003077,9,3.8,제5등급,22,...,0.120513,0.135897,제주,0,1,0,1,0,1,0
106730,3,8,인자무적,3102254,안득수,003053,10,1.8,제5등급,28,...,0.115152,0.093939,제주,0,0,0,1,0,1,0
106731,4,5,캡틴파도,3101700,원유일,003075,1,2.7,제5등급,21,...,0.170455,0.099432,제주,0,0,0,1,0,1,0
106732,5,8,뚜벅이,3018679,문현진,003080,3,1.8,제5등급,23,...,0.109333,0.096000,제주,0,0,0,1,0,1,0
106733,4,2,동백미인,3019049,곽석,003094,1,1.8,제4등급,45,...,0.109333,0.096000,제주,0,1,0,1,0,1,0

In [50]:
# 202207~202306: test
train = df[df['rcDate']<20220701]
test = df[df['rcDate']>=20220701]

In [51]:
print(len(train))
print(len(test))

81447
25287

# test 고유 경기 번호 부여

In [52]:
test = test.reset_index(drop=True)
test.head()

,age,chulNo,hrName,hrNo,jkName,jkNo,ord,plcOdds,rank,rating,...,trord1Rate,trord2Rate,meet2,sex_수,sex_암,meet_서울,meet_제주,prdName_외산,jeju_제주,jeju_한라
0,4,8,원더풀킹,42628,서강주,080605,3,7.4,혼3등급,63,...,0.101523,0.086294,부산경남,1,0,0,0,0,0,0
1,4,10,원더풀페이거,42260,김혜선,080456,2,2.6,혼3등급,54,...,0.125523,0.138075,부산경남,1,0,0,0,0,0,0
2,4,7,골든벼락,45213,페로비치,080542,1,1.3,혼3등급,58,...,0.199248,0.127820,부산경남,1,0,0,0,1,0,0
3,4,2,다이아포스,42860,서강주,080605,8,2.4,국5등급,35,...,0.092593,0.074074,부산경남,0,0,0,0,0,0,0
4,3,3,동부스타,43841,정도윤,080565,7,2.7,국5등급,30,...,0.072289,0.078313,부산경남,1,0,0,0,0,0,0

In [53]:
test.shape

(25287, 46)

In [55]:
unique_df = test[['rcDate', 'rcNo', 'meet2']].drop_duplicates().reset_index(drop=True)
unique_df.head()

     rcDate  rcNo meet2
0  20220701     7  부산경남
1  20220701     6  부산경남
2  20220701     5  부산경남
3  20220701     1    제주
4  20220701     1  부산경남

In [67]:
unique_df.shape

(2415, 3)

In [56]:
test['unique_rcNo'] = np.nan

In [64]:
def unique_rcNo(row):
  d = row['rcDate']
  n = row['rcNo']
  m = row['meet2']

  new = unique_df[(unique_df['rcDate']==d)&(unique_df['rcNo']==n)&(unique_df['meet2']==m)].index[0]

  return new

In [65]:
test['unique_rcNo'] = test.apply(unique_rcNo, axis=1)

In [66]:
test['unique_rcNo'].unique()

array([   0,    1,    2, ..., 2412, 2413, 2414])

In [68]:
test[test['unique_rcNo'].isna()]

Empty DataFrame
Columns: [age, chulNo, hrName, hrNo, jkName, jkNo, ord, plcOdds, rank, rating, rcDate, rcDist, rcName, rcNo, rcTime, trName, trNo, wgBudam, wgHr, winOdds, jkAge, jkCareer, trCareer, waterPercent, trTime_14, trTime_30, recent_jinryo, recent_ill, wgHr_var, y_speed, y_ord, hrrank, ord1Rate, ord2Rate, jkord1Rate, jkord2Rate, trord1Rate, trord2Rate, meet2, sex_수, sex_암, meet_서울, meet_제주, prdName_외산, jeju_제주, jeju_한라, unique_rcNo]
Index: []

[0 rows x 47 columns]

In [71]:
test = test.drop(['meet2'], axis=1)

In [72]:
test.columns

Index(['age', 'chulNo', 'hrName', 'hrNo', 'jkName', 'jkNo', 'ord', 'plcOdds',
       'rank', 'rating', 'rcDate', 'rcDist', 'rcName', 'rcNo', 'rcTime',
       'trName', 'trNo', 'wgBudam', 'wgHr', 'winOdds', 'jkAge', 'jkCareer',
       'trCareer', 'waterPercent', 'trTime_14', 'trTime_30', 'recent_jinryo',
       'recent_ill', 'wgHr_var', 'y_speed', 'y_ord', 'hrrank', 'ord1Rate',
       'ord2Rate', 'jkord1Rate', 'jkord2Rate', 'trord1Rate', 'trord2Rate',
       'sex_수', 'sex_암', 'meet_서울', 'meet_제주', 'prdName_외산', 'jeju_제주',
       'jeju_한라', 'unique_rcNo'],
      dtype='object')

## 데이터 저장

In [ ]:
# train.to_csv('/content/drive/MyDrive/데싸 팀플/df_train.csv')
# test.to_csv('/content/drive/MyDrive/데싸 팀플/df_test.csv')

In [73]:
test.to_csv('/content/drive/MyDrive/데싸 팀플/df_test2.csv')